update version to 0.5.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1545,7 +1545,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=netcat
- VERSION=0.4.0
+ VERSION=0.5.0
 
 
 cat >>confdefs.h <<_ACEOF
@@ -6631,6 +6631,64 @@ _ACEOF
 
 fi
 done
+
+
+echo "$as_me:$LINENO: checking for struct in_pktinfo" >&5
+echo $ECHO_N "checking for struct in_pktinfo... $ECHO_C" >&6
+if test "${ac_cv_type_struct_in_pktinfo+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <netinet/in.h>
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+if ((struct in_pktinfo *) 0)
+  return 0;
+if (sizeof (struct in_pktinfo))
+  return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_type_struct_in_pktinfo=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_type_struct_in_pktinfo=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_type_struct_in_pktinfo" >&5
+echo "${ECHO_T}$ac_cv_type_struct_in_pktinfo" >&6
+if test $ac_cv_type_struct_in_pktinfo = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_PKTINFO
+_ACEOF
+
+fi
 
 
 
